build_from:
  aarch64: "ghcr.io/hassio-addons/base-aarch64:15.0.8"
  amd64: "ghcr.io/hassio-addons/base-amd64:15.0.8"
  armhf: "ghcr.io/hassio-addons/base-armhf:15.0.8"
  armv7: "ghcr.io/hassio-addons/base-armv7:15.0.8"
  i386: "ghcr.io/hassio-addons/base-i386:15.0.8"
labels:
  org.opencontainers.image.title: "Forgejo"
  org.opencontainers.image.description: "A lightweight self-hosted Git service"
  org.opencontainers.image.source: "https://github.com/yourusername/forgejo-addon"
  org.opencontainers.image.licenses: "MIT"
args: {}
