build_from:
  amd64: "ghcr.io/hassio-addons/base-amd64:15.0.8"
  aarch64: "ghcr.io/hassio-addons/base-aarch64:15.0.8"
labels:
  org.opencontainers.image.title: "Forgejo"
  org.opencontainers.image.description: "A lightweight self-hosted Git service"
  org.opencontainers.image.source: "https://github.com/yourusername/forgejo-addon"
  org.opencontainers.image.licenses: "MIT"
args: {}
